name: brew test-bot
on:
  push:
    branches:
      - main
      - update/**

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test-bot:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    permissions:
      actions: read
      checks: read
      contents: read
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v5
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-${{ runner.arch }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-${{ runner.arch }}-rubygems-

      - name: Cleanup before
        run: brew test-bot --only-cleanup-before

      - name: Setup
        run: brew test-bot --only-setup

      - name: Tap syntax
        run: brew test-bot --only-tap-syntax

      - name: Setup Hell
        if: startsWith(github.ref, 'refs/heads/update/')
        uses: ./.github/actions/setup-hell

      - name: Extract formula from branch
        id: formula
        if: startsWith(github.ref, 'refs/heads/update/')
        run: ./scripts/extract-formula-name.hell

      - name: Build bottles
        id: build
        if: startsWith(github.ref, 'refs/heads/update/')
        env:
          FORMULA_NAME: ${{ steps.formula.outputs.name }}
        run: >
          brew test-bot
          --only-formulae
          --only-json-tab
          --skip-dependents
          --testing-formulae="$FORMULA_NAME"
        timeout-minutes: 90

      - name: Upload bottles as artifact
        if: always() && steps.build.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'
          if-no-files-found: error
